Replace isipv6 method with builtin package
bit-team/backintime pull request #1689
Opened 2024-04-15 06:56 UTC by jarbhav

- Removed `isIPv6Address()`  function and related tests
- Using `ipaddress` package directly in the `escapeIPv6Address` function

2024-04-15 07:32 UTC, buhtz commented
Great. Looks nice. Good work.

2024-04-15 16:18 UTC, jarbhav commented
Hey Christian, I am unable to see the review comments.
I will get started on the test cases.

2024-04-15 16:46 UTC, buhtz commented
Dear Vaibhav,

On 2024-04-15 09:19 Vaibhav Raj ***@***.***> wrote:
> Hey Christian, I am unable to see the review comments.
> I will get started on the test cases.

I wonder how this could be. Do you read via email or do you visit
github.com? When you visit github.com and visit your on PR you will see
something like this (see attached screenshot). I added two circles with
numbers to the picture to point you to the comments.

Can't you see this on the real github.com website?

Kind
Christian

2024-04-15 17:18 UTC, jarbhav commented
![image](https://github.com/bit-team/backintime/assets/60002889/a64ee6c2-d01f-42a1-90c7-090469e9e4cf)

2024-04-15 18:04 UTC, buhtz commented
Your screenshot looks like the "Files changed" section. My apologize. I think the term I used (code comments) is not correct. Correct would be review comments. Have a look at this screencast. Does this help you?
![Peek 2024-04-15 20-02](https://github.com/bit-team/backintime/assets/11861496/e4043943-f7f3-4525-9707-416d655a5fa2)

2024-04-23 07:06 UTC, buhtz commented
Dear Vaibhav,
can I somehow be of assistance?
Kind,
Christian

2024-05-01 20:32 UTC, buhtz requested changes

2024-05-01 20:32 UTC, buhtz commented on common/tools.py
>      Escape IPv6 Addresses with square brackets ``[]``.
Please modify the doc string to something like this

```
    """Escape IP addresses with square brackets ``[]`` if they are IPv6.

    If IPv4 nothing is changed.

    Args:
        address (str): IP-Address to escape if needed.

    Returns:
        str: The address, escaped if it is IPv6.

    Raises:
        ValueError: If address is not a valid IPv4 or IPv6.
    """
```

2024-05-01 20:32 UTC, buhtz commented on common/tools.py
> +        pass    # Address is not a valid IP address, so return it unchanged
I wonder if we might lose some error cases when catching an exception here. I would prefer to see exceptions. Please remove the try-catch block.

```suggestion
    ip = ipaddress.ip_address(address)
    if ip.version == 6:
        return '[{}]'.format(address)
```

2024-05-11 12:17 UTC, buhtz commented
Dear Vaibhav,
can you please give us some feedback about your plans and your next steps.
Best,
Christian

2024-05-12 14:19 UTC, jarbhav commented
Hey Christian,
I apologize for the lack of response; I will try to get back to you with all the changes above in the coming 3 days.
Please let me know if this should be done sooner.
Vaibhav

2024-05-12 15:34 UTC, buhtz commented
Dear Vaibhav,
Thank you for the reply.

> I will try to get back to you with all the changes above in the coming 3 days. Please let me know if this should be done sooner.

That is totally fine for me. Take your time. No need to hurry. I just need to know your schedule to "integrate" your PR into the rest of our workflow and tasks.

Best,
Chstian

2024-05-13 19:06 UTC, jarbhav commented
Dear Christian,
I have made the suggested changes, also separated the test method into three different methods. Please let me know if any changes are required

Vaibhav

2024-05-21 10:25 UTC, buhtz commented
Dear Vaibhav,
please apologize my late reply. Your modifications looking good. I just did some refactoring and thing we are now ready to merge. I will merge in some days after a cool down period. Please see [What happens after you opened a Pull Request (PR)?](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#what-happens-after-you-opened-a-pull-request-PR) about how we handle this usually.

- I refactored the unit tests a bit.
- I rewinded my ValueError proposal. Other tests failed because they where using host names (e.g. "localhost").

2024-05-21 10:26 UTC, buhtz approved these changes

2024-05-21 10:46 UTC, jarbhav commented
Thanks Christian

2024-05-23 19:15 UTC, merged