doc(FAQ): What happens when I remove a snapshot (#875)
bit-team/backintime pull request #1774
Opened 2024-07-01 00:18 UTC by DerekVeit

Don't forget the changelog entry! ;)

Did you run "codespell"?

2024-07-02 08:46 UTC, buhtz requested changes
Hello Derek,

On behalf of the team, thank you for your contribution and taking
the time to improve Back In Time. We appreciate it.

Your PR looks fine, despite my one suggestion for a modification.
It will get merged after a cool off period.
To find out how we usually tread PRs please read
["What happens after you opened a PullRequest (PR)?"](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#what-happens-after-you-opened-a-pull-request-PR).

Best,
Christian

2024-07-02 08:46 UTC, buhtz commented on FAQ.md
> +others, so other snapshots are not affected, but the data of identical files is
```suggestion
others, so other snapshots are not affected. However, the data of identical files is
```

2024-07-02 14:02 UTC, buhtz approved these changes

2024-07-04 22:12 UTC, aryoda approved these changes

2024-07-05 08:19 UTC, merged