Worked on fixing issue W0612, unused-variable
bit-team/backintime pull request #1790
Opened 2024-07-11 03:42 UTC by dnerever

Fixed the occurrence of unused variables through multiple files within `/common`

2024-07-11 07:13 UTC, buhtz commented
Thank you for that PR. You see it can get complicated. I added some comments. Let me know how you want to proceed.

Because of its complexity and possible impact I schedule that PR until the upcoming release (see milestone).

2024-07-12 03:19 UTC, dnerever commented
Hey Christian,
Can you direct me to where you added your comments. 

I do see how it can get complicated so delaying it makes sense. Any suggestions for ensuring my future PRs avoid introducing complexity? I'm going now to take a look at the other opens issues in the repo.

Thanks again for all the help!

2024-07-12 07:56 UTC, buhtz commented
You are not the one making it complicated. The old and smelly Back In Time code does. I just tried to pointing out that even simple modifications can become complicated in old code base like Back In Time has.

About the comments. I added 4 comments directly to the diff-like output. This means a comment is connected directly to a line in the code. I marked them with yellow circles in this screenshot. Just scroll up.

![image](https://github.com/user-attachments/assets/22892e68-f65e-4380-8957-c5dfc828d1bb)

2024-07-13 06:35 UTC, buhtz approved these changes

2024-07-13 06:35 UTC, buhtz commented on common/config.py
> +                firstDay = firstDay.replace(month = firstDay.month - 1)
What is the rational behind this? The for loop is gone.

I assume the iteration is needed but the iteration counter not. In this case someone should write

    for _ in range(values-1):
        foobar()

The `_` is an accepted variable name in the Python world for "unnamed" variables.

But this method seems to be very important. We could break a lot if something is wrong here.
I will have a look if there is a good unit test for this method and if not I would write one. Or do you want to write a unit test?

2024-07-13 06:35 UTC, buhtz commented on common/schedule.py
> -            grep = subprocess.run(
Great. This is my own code introduced not long ago. ;)

Absolutely right this modificiation.

2024-07-13 06:35 UTC, buhtz commented on common/sshtools.py
> -            for i in range(2):
The whole method is unclear to me what its purpose is.
This for-loop makes no sense to me. But I assume there is one.

If you don't have an idea I would recommend to reset that modification and we remember that in a new issue.

2024-07-13 06:35 UTC, buhtz commented on common/sshtools.py
> -                out, err = proc.communicate()
You can keep that modification. That is ok.

2024-07-13 06:35 UTC, buhtz commented on common/config.py
> +                firstDay = firstDay.replace(month = firstDay.month - 1)
I introduced #1791 . So just reset this modification and leave it as it is. We will take care of it another time.

2024-08-06 15:11 UTC, buhtz commented
Just want to mention that someone else will work on the same rule but in "qt" folder.

https://github.com/bit-team/backintime/issues/1755#issuecomment-2271453055

2024-08-06 15:15 UTC, buhtz requested changes
Please see my last comment.

2024-08-11 15:15 UTC, buhtz commented
I see why you didn't enable W0612 by default. There are to many errors.

2024-08-11 15:16 UTC, buhtz approved these changes

2024-08-11 15:20 UTC, merged